export const ERROR_CODES = {
  AUTH_FAILED: 'E_AUTH_FAILED',
  ACCESS_DENIED: 'E_ACCESS_DENIED',
  FORBIDDEN: 'E_FORBIDDEN',
  FILE_NOT_FOUND: 'E_FILE_NOT_FOUND',
  KEY_EXPIRED: 'E_KEY_EXPIRED',
  PERMISSION_DENIED: 'E_PERMISSION_DENIED',
  READ_ONLY_MODE: 'E_READ_ONLY_MODE',
  VALIDATION_FAILED: 'E_VALIDATION_FAILED',
  TASK_CONFLICT: 'E_TASK_CONFLICT',
  COMMENT_CONFLICT: 'E_COMMENT_CONFLICT',
  COMMENT_NOT_FOUND: 'E_COMMENT_NOT_FOUND',
  DB_LOCK_UNSAFE: 'E_DB_LOCK_UNSAFE',
  DB_CORRUPT: 'E_DB_CORRUPT',
  MIGRATION_REQUIRED: 'E_MIGRATION_REQUIRED',
  BACKUP_RESTORE_FAILED: 'E_BACKUP_RESTORE_FAILED',
  AUDIT_ARCHIVE_FAILED: 'E_AUDIT_ARCHIVE_FAILED',
  CONNECTOR_SECRET_MISSING: 'E_CONNECTOR_SECRET_MISSING',
  ARCHIVE_PURGE_DRYRUN_REQUIRED: 'E_ARCHIVE_PURGE_DRYRUN_REQUIRED'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
